alter table if exists aiot_customer drop constraint if exists FK647clubuh928va0yrrnsgjiw7;
alter table if exists aiot_generic_metric drop constraint if exists FKar0ltvo7ryuogiarllu3t07x7;
alter table if exists aiot_photo drop constraint if exists FKdw430bkxsme3bpuauocjj6wvi;
alter table if exists aiot_photo drop constraint if exists FKl43i7ehygtns5aomd6kt6dfht;
alter table if exists aiot_supplement_log drop constraint if exists FKcywa28c04ldnhqlcffp8b9fw3;
alter table if exists aiot_supplement_log drop constraint if exists FK9xgn7i9btsru6y2qomy7cell3;
drop table if exists aiot_coach cascade;
drop table if exists aiot_customer cascade;
drop table if exists aiot_generic_metric cascade;
drop table if exists aiot_generic_metric_type cascade;
drop table if exists aiot_photo cascade;
drop table if exists aiot_supplement_log cascade;
drop table if exists aiot_supplement_type cascade;
drop sequence if exists aiot_coach_seq;
drop sequence if exists aiot_customer_seq;
drop sequence if exists aiot_generic_metric_seq;
drop sequence if exists aiot_generic_metric_type_seq;
drop sequence if exists aiot_photo_seq;
drop sequence if exists aiot_supplement_seq;
drop sequence if exists aiot_supplement_type_seq;
alter table if exists aiot_customer drop constraint if exists FK647clubuh928va0yrrnsgjiw7;
alter table if exists aiot_generic_metric drop constraint if exists FKar0ltvo7ryuogiarllu3t07x7;
alter table if exists aiot_photo drop constraint if exists FKdw430bkxsme3bpuauocjj6wvi;
alter table if exists aiot_photo drop constraint if exists FKl43i7ehygtns5aomd6kt6dfht;
alter table if exists aiot_supplement_log drop constraint if exists FKcywa28c04ldnhqlcffp8b9fw3;
alter table if exists aiot_supplement_log drop constraint if exists FK9xgn7i9btsru6y2qomy7cell3;
drop table if exists aiot_coach cascade;
drop table if exists aiot_customer cascade;
drop table if exists aiot_generic_metric cascade;
drop table if exists aiot_generic_metric_type cascade;
drop table if exists aiot_photo cascade;
drop table if exists aiot_supplement_log cascade;
drop table if exists aiot_supplement_type cascade;
drop sequence if exists aiot_coach_seq;
drop sequence if exists aiot_customer_seq;
drop sequence if exists aiot_generic_metric_seq;
drop sequence if exists aiot_generic_metric_type_seq;
drop sequence if exists aiot_photo_seq;
drop sequence if exists aiot_supplement_seq;
drop sequence if exists aiot_supplement_type_seq;
alter table if exists aiot_customer drop constraint if exists FK647clubuh928va0yrrnsgjiw7;
alter table if exists aiot_generic_metric drop constraint if exists FKar0ltvo7ryuogiarllu3t07x7;
alter table if exists aiot_photo drop constraint if exists FKdw430bkxsme3bpuauocjj6wvi;
alter table if exists aiot_photo drop constraint if exists FKl43i7ehygtns5aomd6kt6dfht;
alter table if exists aiot_supplement_log drop constraint if exists FKcywa28c04ldnhqlcffp8b9fw3;
alter table if exists aiot_supplement_log drop constraint if exists FK9xgn7i9btsru6y2qomy7cell3;
drop table if exists aiot_coach cascade;
drop table if exists aiot_customer cascade;
drop table if exists aiot_generic_metric cascade;
drop table if exists aiot_generic_metric_type cascade;
drop table if exists aiot_photo cascade;
drop table if exists aiot_supplement_log cascade;
drop table if exists aiot_supplement_type cascade;
drop sequence if exists aiot_coach_seq;
drop sequence if exists aiot_customer_seq;
drop sequence if exists aiot_generic_metric_seq;
drop sequence if exists aiot_generic_metric_type_seq;
drop sequence if exists aiot_photo_seq;
drop sequence if exists aiot_supplement_seq;
drop sequence if exists aiot_supplement_type_seq;
alter table if exists aiot_customer drop constraint if exists FK647clubuh928va0yrrnsgjiw7;
alter table if exists aiot_generic_metric drop constraint if exists FKar0ltvo7ryuogiarllu3t07x7;
alter table if exists aiot_photo drop constraint if exists FKdw430bkxsme3bpuauocjj6wvi;
alter table if exists aiot_photo drop constraint if exists FKl43i7ehygtns5aomd6kt6dfht;
alter table if exists aiot_supplement_log drop constraint if exists FKcywa28c04ldnhqlcffp8b9fw3;
alter table if exists aiot_supplement_log drop constraint if exists FK9xgn7i9btsru6y2qomy7cell3;
drop table if exists aiot_coach cascade;
drop table if exists aiot_customer cascade;
drop table if exists aiot_generic_metric cascade;
drop table if exists aiot_generic_metric_type cascade;
drop table if exists aiot_photo cascade;
drop table if exists aiot_supplement_log cascade;
drop table if exists aiot_supplement_type cascade;
drop sequence if exists aiot_coach_seq;
drop sequence if exists aiot_customer_seq;
drop sequence if exists aiot_generic_metric_seq;
drop sequence if exists aiot_generic_metric_type_seq;
drop sequence if exists aiot_photo_seq;
drop sequence if exists aiot_supplement_seq;
drop sequence if exists aiot_supplement_type_seq;
alter table if exists aiot_customer drop constraint if exists FK647clubuh928va0yrrnsgjiw7;
alter table if exists aiot_generic_metric drop constraint if exists FKar0ltvo7ryuogiarllu3t07x7;
alter table if exists aiot_photo drop constraint if exists FKdw430bkxsme3bpuauocjj6wvi;
alter table if exists aiot_photo drop constraint if exists FKl43i7ehygtns5aomd6kt6dfht;
alter table if exists aiot_supplement_log drop constraint if exists FKcywa28c04ldnhqlcffp8b9fw3;
alter table if exists aiot_supplement_log drop constraint if exists FK9xgn7i9btsru6y2qomy7cell3;
drop table if exists aiot_coach cascade;
drop table if exists aiot_customer cascade;
drop table if exists aiot_generic_metric cascade;
drop table if exists aiot_generic_metric_type cascade;
drop table if exists aiot_photo cascade;
drop table if exists aiot_supplement_log cascade;
drop table if exists aiot_supplement_type cascade;
drop sequence if exists aiot_coach_seq;
drop sequence if exists aiot_customer_seq;
drop sequence if exists aiot_generic_metric_seq;
drop sequence if exists aiot_generic_metric_type_seq;
drop sequence if exists aiot_photo_seq;
drop sequence if exists aiot_supplement_seq;
drop sequence if exists aiot_supplement_type_seq;
alter table if exists aiot_customer drop constraint if exists FK647clubuh928va0yrrnsgjiw7;
alter table if exists aiot_generic_metric drop constraint if exists FKar0ltvo7ryuogiarllu3t07x7;
alter table if exists aiot_photo drop constraint if exists FKdw430bkxsme3bpuauocjj6wvi;
alter table if exists aiot_photo drop constraint if exists FKl43i7ehygtns5aomd6kt6dfht;
alter table if exists aiot_supplement_log drop constraint if exists FKcywa28c04ldnhqlcffp8b9fw3;
alter table if exists aiot_supplement_log drop constraint if exists FK9xgn7i9btsru6y2qomy7cell3;
drop table if exists aiot_coach cascade;
drop table if exists aiot_customer cascade;
drop table if exists aiot_generic_metric cascade;
drop table if exists aiot_generic_metric_type cascade;
drop table if exists aiot_photo cascade;
drop table if exists aiot_supplement_log cascade;
drop table if exists aiot_supplement_type cascade;
drop sequence if exists aiot_coach_seq;
drop sequence if exists aiot_customer_seq;
drop sequence if exists aiot_generic_metric_seq;
drop sequence if exists aiot_generic_metric_type_seq;
drop sequence if exists aiot_photo_seq;
drop sequence if exists aiot_supplement_seq;
drop sequence if exists aiot_supplement_type_seq;
alter table if exists aiot_customer drop constraint if exists FK647clubuh928va0yrrnsgjiw7;
alter table if exists aiot_generic_metric drop constraint if exists FKar0ltvo7ryuogiarllu3t07x7;
alter table if exists aiot_photo drop constraint if exists FKdw430bkxsme3bpuauocjj6wvi;
alter table if exists aiot_photo drop constraint if exists FKl43i7ehygtns5aomd6kt6dfht;
alter table if exists aiot_supplement_log drop constraint if exists FKcywa28c04ldnhqlcffp8b9fw3;
alter table if exists aiot_supplement_log drop constraint if exists FK9xgn7i9btsru6y2qomy7cell3;
drop table if exists aiot_coach cascade;
drop table if exists aiot_customer cascade;
drop table if exists aiot_generic_metric cascade;
drop table if exists aiot_generic_metric_type cascade;
drop table if exists aiot_photo cascade;
drop table if exists aiot_supplement_log cascade;
drop table if exists aiot_supplement_type cascade;
drop sequence if exists aiot_coach_seq;
drop sequence if exists aiot_customer_seq;
drop sequence if exists aiot_generic_metric_seq;
drop sequence if exists aiot_generic_metric_type_seq;
drop sequence if exists aiot_photo_seq;
drop sequence if exists aiot_supplement_seq;
drop sequence if exists aiot_supplement_type_seq;
alter table if exists aiot_customer drop constraint if exists FK647clubuh928va0yrrnsgjiw7;
alter table if exists aiot_generic_metric drop constraint if exists FKar0ltvo7ryuogiarllu3t07x7;
alter table if exists aiot_photo drop constraint if exists FKdw430bkxsme3bpuauocjj6wvi;
alter table if exists aiot_photo drop constraint if exists FKl43i7ehygtns5aomd6kt6dfht;
alter table if exists aiot_supplement_log drop constraint if exists FKcywa28c04ldnhqlcffp8b9fw3;
alter table if exists aiot_supplement_log drop constraint if exists FK9xgn7i9btsru6y2qomy7cell3;
drop table if exists aiot_coach cascade;
drop table if exists aiot_customer cascade;
drop table if exists aiot_generic_metric cascade;
drop table if exists aiot_generic_metric_type cascade;
drop table if exists aiot_photo cascade;
drop table if exists aiot_supplement_log cascade;
drop table if exists aiot_supplement_type cascade;
drop sequence if exists aiot_coach_seq;
drop sequence if exists aiot_customer_seq;
drop sequence if exists aiot_generic_metric_seq;
drop sequence if exists aiot_generic_metric_type_seq;
drop sequence if exists aiot_photo_seq;
drop sequence if exists aiot_supplement_seq;
drop sequence if exists aiot_supplement_type_seq;
