create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
create sequence aiot_user_seq start with 1 increment by 1;
create table aiot_user (id bigint not null, name varchar(255), primary key (id));
