create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
create sequence aiot_coach_seq start with 1 increment by 1;
create sequence aiot_customer_seq start with 1 increment by 1;
create sequence aiot_generic_metric_seq start with 1 increment by 1;
create sequence aiot_generic_metric_type_seq start with 1 increment by 1;
create sequence aiot_photo_seq start with 1 increment by 1;
create table aiot_coach (id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_customer (coach_id bigint, id bigint not null, email varchar(255), name varchar(255), primary key (id));
create table aiot_generic_metric (generic_metric_type_id bigint, id bigint not null, time timestamp(6), primary key (id));
create table aiot_generic_metric_type (id bigint not null, description varchar(255), name varchar(255), unit varchar(255), primary key (id));
create table aiot_photo (generic_metric_id bigint, id bigint not null, photo_id bigint unique, description varchar(255), primary key (id));
alter table if exists aiot_customer add constraint FK647clubuh928va0yrrnsgjiw7 foreign key (coach_id) references aiot_coach;
alter table if exists aiot_generic_metric add constraint FKar0ltvo7ryuogiarllu3t07x7 foreign key (generic_metric_type_id) references aiot_generic_metric_type;
alter table if exists aiot_photo add constraint FKdw430bkxsme3bpuauocjj6wvi foreign key (photo_id) references aiot_customer;
alter table if exists aiot_photo add constraint FKl43i7ehygtns5aomd6kt6dfht foreign key (generic_metric_id) references aiot_generic_metric;
