drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
drop table if exists aiot_user cascade;
drop sequence if exists aiot_user_seq;
